import express from 'express';
import PDFDocument from 'pdfkit';
import { supabase } from '../../config/database.js';
import { logger } from '../../utils/logger.js';

const router = express.Router();

async function buildReportData(orgId) {
  const monthStart = new Date(new Date().getFullYear(), new Date().getMonth(), 1);

  const { data: org } = await supabase
    .from('organisations').select('name, plan, plan_agent_limit').eq('id', orgId).single();

  const { data: agents } = await supabase
    .from('agents').select('id, name, provider').eq('org_id', orgId);

  const { data: logs } = await supabase
    .from('api_logs').select('agent_id, agent_name, cost, value, created_at')
    .eq('org_id', orgId).gte('created_at', monthStart.toISOString());

  const perAgent = {};
  (agents || []).forEach(a => { perAgent[a.id] = { id: a.id, name: a.name, provider: a.provider, cost: 0, value: 0, tasks: 0 }; });

  (logs || []).forEach(l => {
    const key = l.agent_id || l.agent_name;
    if (!perAgent[key]) perAgent[key] = { id: key, name: l.agent_name || 'Unknown', provider: 'unknown', cost: 0, value: 0, tasks: 0 };
    perAgent[key].cost += Number(l.cost || 0);
    perAgent[key].value += Number(l.value || 0);
    perAgent[key].tasks += 1;
  });

  const agentRows = Object.values(perAgent).map(a => ({
    ...a,
    roi: a.cost > 0 ? a.value / a.cost : null,
    status: a.cost === 0 && a.value === 0 ? 'no_data' : a.cost > 0 && a.value / a.cost >= 3 ? 'profitable' : a.cost > 0 && a.value / a.cost >= 1 ? 'marginal' : 'losing',
  }));

  const totalSpend = agentRows.reduce((s, a) => s + a.cost, 0);
  const totalValue = agentRows.reduce((s, a) => s + a.value, 0);
  const netRoi = totalSpend > 0 ? totalValue / totalSpend : null;
  const wasteful = agentRows.filter(a => a.roi != null && a.roi < 1).reduce((s, a) => s + a.cost, 0);

  return {
    org_name: org?.name || 'Organization',
    period: { start: monthStart.toISOString(), end: new Date().toISOString(), label: monthStart.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) },
    kpis: { total_spend: totalSpend, total_value: totalValue, net_roi: netRoi, wasteful_spend: wasteful, agents_count: agentRows.length, tasks_count: (logs || []).length },
    agents: agentRows.sort((a, b) => b.cost - a.cost),
    has_data: totalSpend > 0 || totalValue > 0,
  };
}

function renderReportPdf(doc, data) {
  doc.fontSize(10).fillColor('#888').text('layeroi', 50, 50);
  doc.fontSize(10).fillColor('#888').text(data.period.label.toUpperCase(), 400, 50, { align: 'right' });
  doc.fontSize(26).fillColor('#050505').font('Times-Italic').text(data.org_name, 50, 100);
  doc.fontSize(14).fillColor('#555').font('Helvetica').text('Monthly P&L — AI agent operations', 50, 135);

  const kpiY = 190;
  [
    { label: 'TOTAL SPEND', value: `$${data.kpis.total_spend.toFixed(0)}` },
    { label: 'VALUE GENERATED', value: `$${data.kpis.total_value.toFixed(0)}` },
    { label: 'NET ROI', value: data.kpis.net_roi != null ? `${data.kpis.net_roi.toFixed(1)}x` : '—' },
  ].forEach((k, i) => {
    const x = 50 + i * 172;
    doc.rect(x, kpiY, 160, 80).fillColor('#f5f5f5').fill();
    doc.fontSize(8).fillColor('#888').font('Courier').text(k.label, x + 12, kpiY + 12);
    doc.fontSize(22).fillColor('#050505').font('Courier-Bold').text(k.value, x + 12, kpiY + 32);
  });

  let y = 300;
  doc.fontSize(14).fillColor('#050505').font('Times-Italic').text('Agent breakdown', 50, y);
  y += 28;
  doc.fontSize(8).fillColor('#888').font('Courier');
  doc.text('AGENT', 50, y); doc.text('COST', 250, y, { width: 70, align: 'right' });
  doc.text('VALUE', 330, y, { width: 70, align: 'right' }); doc.text('ROI', 410, y, { width: 50, align: 'right' });
  doc.text('STATUS', 480, y);
  y += 16; doc.moveTo(50, y).lineTo(562, y).strokeColor('#ddd').stroke(); y += 10;

  if (data.agents.length === 0) {
    doc.fontSize(10).fillColor('#888').font('Helvetica-Oblique').text('No agents connected yet.', 50, y + 20);
  } else {
    data.agents.forEach(a => {
      doc.fontSize(10).fillColor('#050505').font('Helvetica').text(a.name.slice(0, 28), 50, y);
      doc.font('Courier').text(`$${a.cost.toFixed(0)}`, 250, y, { width: 70, align: 'right' });
      doc.text(`$${a.value.toFixed(0)}`, 330, y, { width: 70, align: 'right' });
      doc.text(a.roi != null ? `${a.roi.toFixed(1)}x` : '—', 410, y, { width: 50, align: 'right' });
      const sc = a.status === 'profitable' ? '#22c55e' : a.status === 'marginal' ? '#f59e0b' : a.status === 'losing' ? '#ef4444' : '#888';
      doc.fontSize(8).fillColor(sc).text(a.status.toUpperCase(), 480, y + 2);
      y += 22;
    });
  }

  doc.fontSize(8).fillColor('#aaa').font('Courier').text(
    `Generated by layeroi · ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`,
    50, 720
  );
}

// GET /api/reports/latest
router.get('/api/reports/latest', async (req, res) => {
  try {
    const orgId = req.query.orgId;
    if (!orgId) return res.status(400).json({ error: 'orgId required' });
    const data = await buildReportData(orgId);
    res.json({ success: true, data });
  } catch (err) {
    logger.error('Reports latest error', err);
    res.status(500).json({ success: false, error: err.message });
  }
});

// GET /api/reports/pdf
router.get('/api/reports/pdf', async (req, res) => {
  try {
    const orgId = req.query.orgId;
    if (!orgId) return res.status(400).json({ error: 'orgId required' });
    const data = await buildReportData(orgId);

    const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="layeroi-report.pdf"`);
    doc.pipe(res);
    renderReportPdf(doc, data);
    doc.end();
  } catch (err) {
    logger.error('Reports PDF error', err);
    res.status(500).json({ error: err.message });
  }
});

// POST /api/reports/email
router.post('/api/reports/email', async (req, res) => {
  try {
    const { orgId, email } = req.body;
    if (!orgId || !email) return res.status(400).json({ error: 'orgId and email required' });

    const data = await buildReportData(orgId);
    const chunks = [];
    const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
    doc.on('data', c => chunks.push(c));
    const done = new Promise(r => doc.on('end', r));
    renderReportPdf(doc, data);
    doc.end();
    await done;
    const pdfBuffer = Buffer.concat(chunks);

    const { Resend } = await import('resend');
    const resend = new Resend(process.env.RESEND_API_KEY);

    await resend.emails.send({
      from: 'layeroi <hello@layeroi.com>',
      to: email,
      subject: `Your ${data.period.label} AI agent P&L report`,
      html: `<div style="font-family:Inter,sans-serif;max-width:560px;margin:0 auto;padding:32px;">
        <div style="margin-bottom:24px;font-weight:600;">layer<span style="color:#22c55e;">oi</span></div>
        <h1 style="font-family:Georgia,serif;font-style:italic;font-size:28px;margin:0 0 12px;">${data.period.label} Report</h1>
        <p>Total spend: <strong>$${data.kpis.total_spend.toFixed(0)}</strong> · Value: <strong>$${data.kpis.total_value.toFixed(0)}</strong> · ROI: <strong>${data.kpis.net_roi != null ? data.kpis.net_roi.toFixed(1) + 'x' : '—'}</strong></p>
        <p>Full breakdown in the attached PDF.</p>
      </div>`,
      attachments: [{ filename: `layeroi-report-${data.period.label.replace(' ', '-')}.pdf`, content: pdfBuffer }],
    });

    res.json({ success: true, data: { sent_to: email } });
  } catch (err) {
    logger.error('Reports email error', err);
    res.status(500).json({ error: err.message });
  }
});

export default router;
